// src/components/shared/Navbar/Link.tsx
"use client";

import NextLink from 'next/link';
import { usePathname } from 'next/navigation';

export interface LinkProps {
    icon: JSX.Element;
    href: string;
    label: string;
}

/**
 * Renders a link represented as an icon for the navbar.
 * 
 * If the current path is the same as the href, the css will highlight it.
 */
export const Link = ({ icon, href, label }: LinkProps) => {
    const pathname = usePathname();

    const colors = pathname !== href ? "bg-transparent text-black hover:bg-gray-200" : "bg-black text-white";

    return (
        <li className="relative h-full aspect-square sm:w-auto">
            <NextLink href={href} className={`relative h-full w-full flex justify-center items-center rounded-md ${colors} sm:px-5`}>
                {icon}
                <p className="hidden sm:flex relative h-full justify-center items-center">
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    <span>{label}</span>
                </p>
            </NextLink>
        </li>
    )
}

// src/lib/components/shared/Navbar/Link.svelte
<script lang="ts">
    import { stripTrailingSlash } from '$/lib/utils/strip-trailing-slash';
    import { base } from '$app/paths';
    import { page } from '$app/stores';
    import { locale } from '$i18n/i18n-svelte';
    import { createEventDispatcher } from 'svelte';

    export let href: string;

    const dispatch = createEventDispatcher();

    $: colors = $page.url.pathname === stripTrailingSlash(`${base}/${$locale}${href}`) ? 'text-indigo-700' : 'text-gray-500';
</script>

<!--
@component

Renders a link represented as an icon for the navbar.

If the current path is the same as the href, the css will highlight it.
-->

<li class="relative w-full">
    <a
        href="{base}/{$locale}{href}"
        on:click={() => dispatch('click')}
        class="relative w-full py-2 flex gap-10 justify-start items-center rounded-md {colors} sm:px-5"
    >
        <slot />
    </a>
</li>
