// src/components/shared/Navbar/Link.tsx
"use client";

import NextLink from 'next/link';
import { usePathname } from 'next/navigation';

export interface LinkProps {
    icon: JSX.Element;
    href: string;
    label: string;
}

/**
 * Renders a link represented as an icon for the navbar.
 * 
 * If the current path is the same as the href, the css will highlight it.
 */
export const Link = ({ icon, href, label }: LinkProps) => {
    const pathname = usePathname();

    const colors = pathname !== href ? "bg-transparent text-black hover:bg-gray-200" : "bg-black text-white";

    return (
        <li className="relative h-full aspect-square sm:w-auto">
            <NextLink href={href} className={`relative h-full w-full flex justify-center items-center rounded-md ${colors} sm:px-5`}>
                {icon}
                <p className="hidden sm:flex relative h-full justify-center items-center">
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    <span>{label}</span>
                </p>
            </NextLink>
        </li>
    )
}

// src/lib/Navbar/Link.svelte
<script lang="ts">
	import { page } from '$app/stores';

	export let href: string;
	export let label: string;

	const colors =
		$page.url.pathname !== href
			? 'bg-transparent text-black dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700'
			: 'bg-black dark:bg-white text-white dark:text-black';
</script>

<!--
@component

Renders a link represented as an icon for the navbar.

If the current path is the same as the href, the css will highlight it.
-->

<li class="relative h-full aspect-square sm:aspect-auto">
	<a {href} class="relative h-full flex justify-center items-center rounded-md {colors} sm:px-5">
		<p class="hidden sm:flex ml-[10px] relative h-full justify-center items-center">
			{label}
		</p>
	</a>
</li>
