// src/components/shared/Navbar/index.tsx
"use client";

import HomeIcon from '@mui/icons-material/HomeWorkRounded';
import WorkIcon from '@mui/icons-material/WorkRounded';
import BlogIcon from '@mui/icons-material/ArticleRounded';
import ContactIcon from '@mui/icons-material/MailRounded';

import { useParams } from "next/navigation";
import { Link } from "./Link";
import { useDictionary } from "@/hooks/useDictionary";

/**
 * Renders a mobile navbar.
 */
export const Navbar = () => {
    const locale = useParams().lang as string;
    const dictionary = useDictionary(locale);

    return (
        <nav className="lg:hidden relative w-full h-20 shadow-[0px_-4px_3px_rgba(50,50,50,0.25)] dark:shadow-[0px_-4px_3px_rgba(10,10,10,0.25)]">
            <ul className="relative w-full h-full py-5 flex justify-evenly items-center">
                <Link href={`/${locale}`} icon={<HomeIcon />} label={dictionary.navigation.home} />
                <Link href={`/${locale}/work`} icon={<WorkIcon />} label={dictionary.navigation.work} />
                <Link href={`/${locale}/blog`} icon={<BlogIcon />} label={dictionary.navigation.blog} />
                <Link href={`/${locale}/contact`} icon={<ContactIcon />} label={dictionary.navigation.contact} />
            </ul>
        </nav>
    )
}

// src/lib/Navbar/Navbar.svelte
<script lang="ts">
	import Link from './Link.svelte';
	import { IconHome as Home, IconLuggage as Work, IconArticle as Blog, IconMailForward as Contact } from '@tabler/icons-svelte';
</script>

<!--
@component

Renders a navbar adapted for devices under 1024px wide.
-->

<nav
	class="lg:hidden relative w-full h-20 shadow-[0px_-4px_3px_rgba(50,50,50,0.25)] dark:shadow-[0px_-4px_3px_rgba(10,10,10,0.25)]"
>
	<ul class="relative w-full h-full py-5 flex justify-evenly items-center">
		<Link href="/" label="Home" icon={Home} />
		<Link href="/work" label="Projects" icon={Work} />
		<Link href="/blog" label="Blog" icon={Blog} />
		<Link href="/contact" label="Contact" icon={Contact} />
	</ul>
</nav>
